### ISSUE TITLE
Puppet is broken in 2018Q1

### ISSUE THREAD

**Issue by lschweiss-wustl** [TritonDataCenter/pkgsrc#100]
```
# puppet
/opt/local/lib/ruby/2.4.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'fast_gettext' (~> 1.1.2) - did find: [fast_gettext-1.6.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.4.0:/opt/local/lib/ruby/gems/2.4.0', execute `gem env` for more information
        from /opt/local/lib/ruby/2.4.0/rubygems/specification.rb:1445:in `block in activate_dependencies'
        from /opt/local/lib/ruby/2.4.0/rubygems/specification.rb:1434:in `each'
        from /opt/local/lib/ruby/2.4.0/rubygems/specification.rb:1434:in `activate_dependencies'
        from /opt/local/lib/ruby/2.4.0/rubygems/specification.rb:1416:in `activate'
        from /opt/local/lib/ruby/2.4.0/rubygems.rb:300:in `block in activate_bin_path'
        from /opt/local/lib/ruby/2.4.0/rubygems.rb:300:in `synchronize'
        from /opt/local/lib/ruby/2.4.0/rubygems.rb:300:in `activate_bin_path'
        from /opt/local/bin/puppet24:23:in `<main>'
```

This happens when upgrading or on a clean install of 2018Q1 on OmniOS CE r151022.   Puppet was working on all previous releases I've used.

**Comment by lschweiss-wustl** [comment]
Still broken on 20181018 release:

```
/opt/local/lib/ruby/2.4.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'fast_gettext' (~> 1.1.2) - did find: [fast_gettext-1.7.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.4.0:/opt/local/lib/ruby/gems/2.4.0', execute `gem env` for more information
        from /opt/local/lib/ruby/2.4.0/rubygems/specification.rb:1445:in `block in activate_dependencies'
        from /opt/local/lib/ruby/2.4.0/rubygems/specification.rb:1434:in `each'
        from /opt/local/lib/ruby/2.4.0/rubygems/specification.rb:1434:in `activate_dependencies'
        from /opt/local/lib/ruby/2.4.0/rubygems/specification.rb:1416:in `activate'
        from /opt/local/lib/ruby/2.4.0/rubygems.rb:300:in `block in activate_bin_path'
        from /opt/local/lib/ruby/2.4.0/rubygems.rb:300:in `synchronize'
        from /opt/local/lib/ruby/2.4.0/rubygems.rb:300:in `activate_bin_path'
        from /opt/local/bin/puppet24:23:in `<main>'

```
