### ISSUE TITLE
python3.7 throws exceptions about missing getifaddrs

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc#175]
```2019-02-06 12:46:14 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/components/discovery.py", line 179, in scan_devices
    results = await hass.async_add_job(_discover, netdisco)
  File "/opt/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/components/discovery.py", line 207, in _discover
    netdisco.scan()
  File "/opt/homeassistant/lib/python3.7/site-packages/netdisco/discovery.py", line 57, in scan
    self.mdns.start()
  File "/opt/homeassistant/lib/python3.7/site-packages/netdisco/mdns.py", line 23, in start
    self.zeroconf = zeroconf.Zeroconf()
  File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf.py", line 1724, in __init__
    interfaces = normalize_interface_choice(interfaces)
  File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf.py", line 1655, in normalize_interface_choice
    return get_all_addresses()
  File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf.py", line 1645, in get_all_addresses
    for iface in ifaddr.get_adapters()
  File "/opt/homeassistant/lib/python3.7/site-packages/ifaddr/_posix.py", line 44, in get_adapters
    retval = libc.getifaddrs(ctypes.byref(addr))
  File "/opt/local/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/opt/local/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: ld.so.1: python3.7: fatal: getifaddrs: can't find symbol```


We (illumos) do have that! http://src.illumos.org/source/xref/illumos-gate/usr/src/lib/libsocket/inet/getifaddrs.c

I think we just might have to add libsocket to the linker libraries?

**Comment by liv3010m** [comment]
Hi there,

I'm having the same problem:

`2020-03-06 11:25:09 ERROR (MainThread) [homeassistant.setup] Error during setup of component zeroconf`
`Traceback (most recent call last):`
`  File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 174, in _async_setup_component`
`    component.setup, hass, processed_config  # type: ignore`
`  File "/opt/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run`
`    result = self.fn(*self.args, **self.kwargs)`
`  File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/components/zeroconf/__init__.py", line 42, in setup`
`    zeroconf = Zeroconf()`
`  File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf/__init__.py", line 2134, in __init__`
`    interfaces, unicast, ip_version, apple_p2p=apple_p2p`
`  File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf/__init__.py", line 2056, in create_sockets`
`    interfaces = normalize_interface_choice(interfaces, ip_version)`
`  File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf/__init__.py", line 1922, in normalize_interface_choice`
`    result.extend(get_all_addresses())`
`  File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf/__init__.py", line 1844, in get_all_addresses`
`    for iface in ifaddr.get_adapters()`
`  File "/opt/homeassistant/lib/python3.7/site-packages/ifaddr/_posix.py", line 44, in get_adapters`
`    retval = libc.getifaddrs(ctypes.byref(addr))`
`  File "/opt/local/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__`
`    func = self.__getitem__(name)`
`  File "/opt/local/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__`
`    func = self._FuncPtr((name_or_ordinal, self))`
`AttributeError: ld.so.1: python3.7: fatal: getifaddrs: can't find symbol`

**Comment by sjorge** [comment]
IIRC you can patch /opt/homeassistant/lib/python3.7/site-packages/ifaddr/_posix.py to use libsocket instead of libc and it works.

**Comment by sjorge** [comment]
Also see https://github.com/pydron/ifaddr/issues/23

**Comment by liv3010m** [comment]
Thanks @sjorge!
